### PR TITLE
Fix: add windows support for tslint path format

### PR DESCRIPTION
**Pull request by bertyhell**
closes: https://github.com/anthraxx/intellij-awesome-console/issues/52

Tested with:
```
ERROR: C:/Users/ControlsSidebar.tsx:216:17 - Calls to 'console' are not allowed.
```

Result:
```
match: C:/Users/ControlsSidebar.tsx:216:17
row: 216
col: 17
path: C:/Users/ControlsSidebar.tsx
```

@anthraxx mention for attention

### CODE REVIEW

**Comment by bertyhell** [comment]
@anthraxx any chance you could have a look at merging this?

**Comment by anthraxx** [comment]
Sure but this only adds a group to the regex, why does this change any of the behavior?

**Comment by bertyhell** [comment]
> Sure but this only adds a group to the regex, why does this change any of the behavior?

because the pipe symbol has a different meaning when it is found withing ()
I think you probably meant to write (\\\\|/) instead of \\\\|/

since (\\\\|/) will match either the string "\\" or the string "/"
but \\\\|/ will try to match the literal string: "\\|/"

**Comment by anthraxx** [comment]
Yes, that's a very good catch actually. I will test this on some envs and get it merged. Thanks

**Comment by anthraxx** [comment]
applied and fixed in f5177c40566b6ff3821eec7669cf84e9a4ebde72

**Pull request closed without merging**
