### PR TITLE
Fix: Config page not visible

### PR DESCRIPTION
**Pull request by holycrepe**
Add Config to plugins.xml as applicationConfigurable extension

### CODE REVIEW

**Comment by holycrepe** [comment]
@anthraxx Upon further testing, this PR makes the config page visible, but the config page displays default values, not current values. Changes made on the config page are saved, but re-opening the config page does not show the new changes. 

Unfortunately I do not know enough about the SDK to fix this issue

**Comment by anthraxx** [comment]
@holycrepe thanks for the feedback, I will be able to have a look on sunday and see if i can release a new version with some of the important fixes.

**Comment by gregallen** [comment]
any chance to merge this?

**Comment by anthraxx** [comment]
applied in master. thanks

**Pull request closed without merging**
