### PR TITLE
Added project to the lambda as it is required now.

### PR DESCRIPTION
**Pull request by tschallacka**
Fixes https://github.com/anthraxx/intellij-awesome-console/issues/83

See this implementation by jetbrains themselves.

https://git.jetbrains.org/?p=idea/community.git;a=blob;f=java/execution/impl/src/com/intellij/execution/filters/ExceptionLineParserImpl.java;h=07bb6d84c6a58195fb1df2c965ddd6f91dc0d1db#l219

Project was added as a requirement for the interface.

### CODE REVIEW

**Comment by tomasstrejcek** [comment]
@anthraxx hello, any plan to release this? :)

**Comment by anthraxx** [comment]
@tomasstrejcek returned from Christmas stuff, gonna handle a release during the weekend :cat:

**Comment by cfecherolle** [comment]
Hi! Sorry to bother you, but is a release planned anytime soon? (nothing too urgent, just checking 😄 )

**Comment by tschallacka** [comment]
@anthraxx When you make the release, could you also add the new interface require method or an empty dummy method in https://github.com/anthraxx/intellij-awesome-console/blob/master/src/awesome/console/AwesomeLinkFilter.java  
as referenced in https://github.com/anthraxx/intellij-awesome-console/issues/87

it needs a 

```
public void onLinkFollowed(com.intellij.openapi.project.Project, com.intellij.openapi.vfs.VirtualFile, com.intellij.openapi.editor.Editor, com.intellij.openapi.editor.Editor) {  
    // TODO: Add method body.
}
```

**Comment by anthraxx** [comment]
Applied via commit 57ebbd699a4576c58b3ca3f0dedaaaeccdf0b43e
thank you very much!

**Pull request closed without merging**
